#!/bin/sh -ex

# The chaining of find and grep was deemded necessary due to find's lack of a
# proper regex implementation in find. Also note that on linux find does not
# support -E like on BSDs.
for file in $(find . | grep -E "$1"); do
  back=$PWD
  cd $(dirname $file)
  $2 $(basename $file)
  cd $back
done
